#!/usr/bin/env bash

BASE_DIR=`dirname $0`

echo 'calling preboot script'

# erase old env variables
unset APP_EXT_PARAM
unset JVM_EXT_PARAM

APP_EXT_PARAM=''
JVM_EXT_PARAM=''

# custom logic starts

if [ "$ENV" = "smoke" ] || [ "$ENV" = "dev" ]; then
  JVM_EXT_PARAM=" -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=8095,suspend=n $JVM_EXT_PARAM "
fi

#JVM_EXT_PARAM="-Xmx2688M -Xms2688M -Xmn960M -Xss256K -XX:MaxMetaspaceSize=256M -XX:MetaspaceSize=256M -XX:+UseConcMarkSweepGC -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:+ExplicitGCInvokesConcurrentAndUnloadsClasses -XX:+CMSClassUnloadingEnabled -XX:+ParallelRefProcEnabled -XX:+CMSScavengeBeforeRemark -XX:+HeapDumpOnOutOfMemoryError $JVM_EXT_PARAM "

JVM_EXT_PARAM="-XX:+PrintGCDetails -XX:+PrintTenuringDistribution -XX:+PrintHeapAtGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps $JVM_EXT_PARAM"

echo "JVM_EXT_PARAM=$JVM_EXT_PARAM"

echo 'preboot done'